const additionalProducts = [
  {
    id: 101,
    title: "Samsung Galaxy S21",
    description: "A flagship smartphone with a stunning display and powerful performance.",
    price: 799,
    discountPercentage: 10.0,
    rating: 4.6,
    stock: 150,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/101/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/101/1.jpg",
      "https://dummyjson.com/image/i/products/101/2.jpg",
    ],
  },
  {
    id: 102,
    title: "Apple iPhone 13",
    description: "The latest iPhone with advanced camera features and A15 Bionic chip.",
    price: 999,
    discountPercentage: 5.0,
    rating: 4.8,
    stock: 100,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/102/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/102/1.jpg",
      "https://dummyjson.com/image/i/products/102/2.jpg",
    ],
  },
  {
    id: 103,
    title: "Google Pixel 6",
    description: "A smartphone with Google's latest AI-powered features.",
    price: 599,
    discountPercentage: 7.5,
    rating: 4.5,
    stock: 120,
    brand: "Google",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/103/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/103/1.jpg",
      "https://dummyjson.com/image/i/products/103/2.jpg",
    ],
  },
  {
    id: 104,
    title: "OnePlus 9 Pro",
    description: "A premium smartphone with Hasselblad camera technology.",
    price: 729,
    discountPercentage: 8.0,
    rating: 4.4,
    stock: 90,
    brand: "OnePlus",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/104/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/104/1.jpg",
      "https://dummyjson.com/image/i/products/104/2.jpg",
    ],
  },
  {
    id: 105,
    title: "Xiaomi Mi 11",
    description: "A high-performance smartphone with an excellent camera setup.",
    price: 699,
    discountPercentage: 9.0,
    rating: 4.3,
    stock: 110,
    brand: "Xiaomi",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/105/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/105/1.jpg",
      "https://dummyjson.com/image/i/products/105/2.jpg",
    ],
  },
  {
    id: 106,
    title: "Sony Xperia 5 III",
    description: "A compact smartphone with advanced photography features.",
    price: 899,
    discountPercentage: 6.0,
    rating: 4.2,
    stock: 80,
    brand: "Sony",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/106/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/106/1.jpg",
      "https://dummyjson.com/image/i/products/106/2.jpg",
    ],
  },
  {
    id: 107,
    title: "Oppo Find X3 Pro",
    description: "A smartphone with a stunning design and powerful performance.",
    price: 749,
    discountPercentage: 7.0,
    rating: 4.5,
    stock: 95,
    brand: "Oppo",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/107/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/107/1.jpg",
      "https://dummyjson.com/image/i/products/107/2.jpg",
    ],
  },
  {
    id: 108,
    title: "Vivo X60 Pro",
    description: "A smartphone with a sleek design and excellent camera features.",
    price: 679,
    discountPercentage: 8.5,
    rating: 4.4,
    stock: 130,
    brand: "Vivo",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/108/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/108/1.jpg",
      "https://dummyjson.com/image/i/products/108/2.jpg",
    ],
  },
  {
    id: 109,
    title: "Realme GT",
    description: "A budget-friendly smartphone with flagship-level performance.",
    price: 499,
    discountPercentage: 10.0,
    rating: 4.3,
    stock: 140,
    brand: "Realme",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/109/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/109/1.jpg",
      "https://dummyjson.com/image/i/products/109/2.jpg",
    ],
  },
  {
    id: 110,
    title: "Asus ROG Phone 5",
    description: "A gaming smartphone with top-notch performance and features.",
    price: 999,
    discountPercentage: 5.5,
    rating: 4.7,
    stock: 70,
    brand: "Asus",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/110/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/110/1.jpg",
      "https://dummyjson.com/image/i/products/110/2.jpg",
    ],
  },
  {
    id: 111,
    title: "Motorola Edge 20",
    description: "A stylish smartphone with a 108MP camera and smooth performance.",
    price: 599,
    discountPercentage: 8.0,
    rating: 4.2,
    stock: 100,
    brand: "Motorola",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/111/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/111/1.jpg",
      "https://dummyjson.com/image/i/products/111/2.jpg",
    ],
  },
  {
    id: 112,
    title: "Huawei P50 Pro",
    description: "A smartphone with an innovative camera system and sleek design.",
    price: 899,
    discountPercentage: 6.5,
    rating: 4.5,
    stock: 85,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/112/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/112/1.jpg",
      "https://dummyjson.com/image/i/products/112/2.jpg",
    ],
  },
  {
    id: 113,
    title: "Nokia X20",
    description: "A durable smartphone with a focus on sustainability.",
    price: 499,
    discountPercentage: 9.0,
    rating: 4.1,
    stock: 150,
    brand: "Nokia",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/113/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/113/1.jpg",
      "https://dummyjson.com/image/i/products/113/2.jpg",
    ],
  },
  {
    id: 114,
    title: "Lenovo Legion Phone Duel 2",
    description: "A gaming smartphone with dual cooling fans and RGB lighting.",
    price: 899,
    discountPercentage: 7.0,
    rating: 4.6,
    stock: 60,
    brand: "Lenovo",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/114/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/114/1.jpg",
      "https://dummyjson.com/image/i/products/114/2.jpg",
    ],
  },
  {
    id: 115,
    title: "ZTE Axon 30 Ultra",
    description: "A smartphone with a 144Hz display and triple 64MP cameras.",
    price: 749,
    discountPercentage: 8.5,
    rating: 4.4,
    stock: 90,
    brand: "ZTE",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/115/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/115/1.jpg",
      "https://dummyjson.com/image/i/products/115/2.jpg",
    ],
  },
  {
    id: 116,
    title: "Honor Magic 3 Pro",
    description: "A premium smartphone with a curved display and powerful performance.",
    price: 899,
    discountPercentage: 6.0,
    rating: 4.5,
    stock: 75,
    brand: "Honor",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/116/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/116/1.jpg",
      "https://dummyjson.com/image/i/products/116/2.jpg",
    ],
  },
  {
    id: 117,
    title: "Meizu 18 Pro",
    description: "A smartphone with a sleek design and Snapdragon 888 processor.",
    price: 799,
    discountPercentage: 7.5,
    rating: 4.3,
    stock: 100,
    brand: "Meizu",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/117/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/117/1.jpg",
      "https://dummyjson.com/image/i/products/117/2.jpg",
    ],
  },
  {
    id: 118,
    title: "Black Shark 4 Pro",
    description: "A gaming smartphone with a 144Hz display and magnetic triggers.",
    price: 699,
    discountPercentage: 8.0,
    rating: 4.6,
    stock: 80,
    brand: "Black Shark",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/118/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/118/1.jpg",
      "https://dummyjson.com/image/i/products/118/2.jpg",
    ],
  },
  {
    id: 119,
    title: "Alcatel 3L",
    description: "An affordable smartphone with a triple-camera setup.",
    price: 199,
    discountPercentage: 12.0,
    rating: 4.0,
    stock: 200,
    brand: "Alcatel",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/119/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/119/1.jpg",
      "https://dummyjson.com/image/i/products/119/2.jpg",
    ],
  },
  {
    id: 120,
    title: "Fairphone 4",
    description: "A sustainable smartphone with modular components.",
    price: 599,
    discountPercentage: 9.0,
    rating: 4.2,
    stock: 90,
    brand: "Fairphone",
    category: "smartphones",
    thumbnail: "https://dummyjson.com/image/i/products/120/thumbnail.jpg",
    images: [
      "https://dummyjson.com/image/i/products/120/1.jpg",
      "https://dummyjson.com/image/i/products/120/2.jpg",
    ],
  },
];

